// ============================================================
// Psyche Feedback Worker — Cloudflare Worker
//
// Receives anonymous diagnostic reports from psyche-ai plugins.
// Auto-creates / appends to GitHub Issues.
//
// Deploy:
//   cd tools/feedback-worker
//   npx wrangler secret put GITHUB_TOKEN   (paste a fine-grained PAT with Issues:write)
//   npx wrangler deploy
//
// Secrets needed:
//   GITHUB_TOKEN — GitHub PAT with repo Issues write permission
//
// The worker URL becomes your feedbackUrl config value.
// ============================================================

interface Env {
  GITHUB_TOKEN: string;
}

interface FeedbackPayload {
  version: string;
  timestamp: string;
  mbti: string;
  issues: Array<{
    id: string;
    severity: string;
    message: string;
    suggestion?: string;
  }>;
  metrics: {
    inputs: number;
    classified: number;
    classifyRate: number;
    chemDelta: number;
    maxChemDelta: number;
    errors: number;
  };
  state: {
    version: number;
    interactions: number;
    agreementStreak: number;
    historyLength: number;
  };
}

// ── Config ────────────────────────────────────────────────────

const GITHUB_OWNER = "Shangri-la-0428";
const GITHUB_REPO = "psyche-ai";
const ISSUE_LABEL = "auto-diagnostic";
const RATE_LIMIT_PER_IP = 10; // max submissions per hour per IP

// ── Helpers ───────────────────────────────────────────────────

function issueSignature(payload: FeedbackPayload): string {
  // Dedup key: sorted issue IDs + psyche version
  const ids = payload.issues.map(i => i.id).sort().join(",");
  return `[${ISSUE_LABEL}] ${ids} (v${payload.version})`;
}

function buildIssueBody(payload: FeedbackPayload): string {
  const lines: string[] = [];

  lines.push("## Auto-Diagnostic Feedback");
  lines.push("");
  lines.push(`- **psyche-ai**: v${payload.version}`);
  lines.push(`- **MBTI**: ${payload.mbti}`);
  lines.push(`- **Time**: ${payload.timestamp}`);
  lines.push(`- **Interactions**: ${payload.state.interactions}`);
  lines.push("");

  lines.push("## Issues");
  lines.push("");
  for (const issue of payload.issues) {
    const icon = issue.severity === "critical" ? "\u{1F534}"
      : issue.severity === "warning" ? "\u{1F7E1}" : "\u{1F535}";
    lines.push(`### ${icon} ${issue.id} (${issue.severity})`);
    lines.push("");
    lines.push(issue.message);
    if (issue.suggestion) {
      lines.push("");
      lines.push(`**\u5EFA\u8BAE**: ${issue.suggestion}`);
    }
    lines.push("");
  }

  lines.push("## Metrics");
  lines.push("");
  lines.push("| Metric | Value |");
  lines.push("|--------|-------|");
  lines.push(`| Inputs | ${payload.metrics.inputs} |`);
  lines.push(`| Classify Rate | ${(payload.metrics.classifyRate * 100).toFixed(0)}% |`);
  lines.push(`| Chemistry Delta | ${payload.metrics.chemDelta} |`);
  lines.push(`| Errors | ${payload.metrics.errors} |`);
  lines.push(`| Agreement Streak | ${payload.state.agreementStreak} |`);
  lines.push("");

  lines.push(`<sub>Auto-generated by psyche-ai diagnostics. No message content included.</sub>`);

  return lines.join("\n");
}

function buildCommentBody(payload: FeedbackPayload): string {
  const ids = payload.issues.map(i => `${i.severity[0]}:${i.id}`).join(", ");
  return [
    `**+1 occurrence** at ${payload.timestamp}`,
    `MBTI: ${payload.mbti} | Interactions: ${payload.state.interactions} | Classify: ${(payload.metrics.classifyRate * 100).toFixed(0)}%`,
    `Issues: ${ids}`,
  ].join("\n");
}

// ── GitHub API ───────────────────────────────────────────────

async function findOpenIssue(title: string, token: string): Promise<number | null> {
  try {
    // Use issues list API (more reliable with OAuth tokens than search API)
    const res = await fetch(
      `https://api.github.com/repos/${GITHUB_OWNER}/${GITHUB_REPO}/issues?state=open&labels=${ISSUE_LABEL}&per_page=30`,
      {
        headers: {
          Authorization: `Bearer ${token}`,
          Accept: "application/vnd.github+json",
          "User-Agent": "psyche-feedback-worker",
        },
      },
    );
    if (!res.ok) return null;
    const issues = await res.json() as Array<{ number: number; title: string }>;
    const match = issues.find(i => i.title === title);
    return match?.number ?? null;
  } catch {
    return null; // Dedup failure is non-fatal — will create a new issue
  }
}

async function createIssue(title: string, body: string, token: string): Promise<number | null> {
  const res = await fetch(`https://api.github.com/repos/${GITHUB_OWNER}/${GITHUB_REPO}/issues`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github+json",
      "User-Agent": "psyche-feedback-worker",
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      title,
      body,
      labels: [ISSUE_LABEL],
    }),
  });
  if (!res.ok) return null;
  const data = await res.json() as { number: number };
  return data.number;
}

async function addComment(issueNumber: number, body: string, token: string): Promise<boolean> {
  const res = await fetch(
    `https://api.github.com/repos/${GITHUB_OWNER}/${GITHUB_REPO}/issues/${issueNumber}/comments`,
    {
      method: "POST",
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: "application/vnd.github+json",
        "User-Agent": "psyche-feedback-worker",
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ body }),
    },
  );
  return res.ok;
}

// ── Rate Limiting (in-memory, resets on worker restart) ──────

const rateLimits = new Map<string, { count: number; resetAt: number }>();

function checkRateLimit(ip: string): boolean {
  const now = Date.now();
  const entry = rateLimits.get(ip);
  if (!entry || now > entry.resetAt) {
    rateLimits.set(ip, { count: 1, resetAt: now + 3600_000 });
    return true;
  }
  if (entry.count >= RATE_LIMIT_PER_IP) return false;
  entry.count++;
  return true;
}

// ── Worker Entry ─────────────────────────────────────────────

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    // CORS preflight
    if (request.method === "OPTIONS") {
      return new Response(null, {
        headers: {
          "Access-Control-Allow-Origin": "*",
          "Access-Control-Allow-Methods": "POST",
          "Access-Control-Allow-Headers": "Content-Type",
        },
      });
    }

    if (request.method !== "POST") {
      return new Response("Method not allowed", { status: 405 });
    }

    // Rate limit
    const ip = request.headers.get("CF-Connecting-IP") ?? "unknown";
    if (!checkRateLimit(ip)) {
      return new Response("Rate limited", { status: 429 });
    }

    // Parse payload
    let payload: FeedbackPayload;
    try {
      payload = await request.json() as FeedbackPayload;
    } catch {
      return new Response("Invalid JSON", { status: 400 });
    }

    // Validate
    if (!payload.version || !payload.issues || !Array.isArray(payload.issues)) {
      return new Response("Invalid payload", { status: 400 });
    }

    // Only actionable issues (critical/warning)
    const actionable = payload.issues.filter(i => i.severity !== "info");
    if (actionable.length === 0) {
      return new Response(JSON.stringify({ action: "skipped", reason: "no actionable issues" }), {
        status: 200,
        headers: { "Content-Type": "application/json" },
      });
    }

    // Check for existing open issue with same signature
    const title = issueSignature(payload);
    const existingNumber = await findOpenIssue(title, env.GITHUB_TOKEN);

    let result: { action: string; issue?: number; error?: string };

    if (existingNumber) {
      // Append as comment — same issue combo already reported
      const ok = await addComment(existingNumber, buildCommentBody(payload), env.GITHUB_TOKEN);
      result = ok
        ? { action: "commented", issue: existingNumber }
        : { action: "comment_failed", issue: existingNumber };
    } else {
      // Create new issue
      const num = await createIssue(title, buildIssueBody(payload), env.GITHUB_TOKEN);
      result = num
        ? { action: "created", issue: num }
        : { action: "create_failed" };
    }

    return new Response(JSON.stringify(result), {
      status: 200,
      headers: {
        "Content-Type": "application/json",
        "Access-Control-Allow-Origin": "*",
      },
    });
  },
};
